using SentinelAI.Core.Enums;

namespace SentinelAI.Core.Entities;

/// <summary>
/// Represents a transaction being analyzed for fraud
/// </summary>
public class TransactionAnalysis : AuditableEntity
{
    public Guid TenantId { get; set; }
    public required string TransactionReference { get; set; }
    public required string ExternalTransactionId { get; set; }
    
    // Transaction details
    public decimal Amount { get; set; }
    public required string Currency { get; set; }
    public TransactionChannel Channel { get; set; }
    public DateTime TransactionTime { get; set; }
    
    // Parties (encrypted for PII protection)
    public string? EncryptedSourceAccount { get; set; }
    public string? EncryptedDestinationAccount { get; set; }
    public string? EncryptedCustomerId { get; set; }
    public string? SourceAccountHash { get; set; }  // For lookups without decryption
    public string? DestinationAccountHash { get; set; }
    
    // Device/Session info
    public string? DeviceFingerprint { get; set; }
    public string? IpAddress { get; set; }
    public string? SessionId { get; set; }
    public string? UserAgent { get; set; }
    
    // Location
    public double? Latitude { get; set; }
    public double? Longitude { get; set; }
    public string? Country { get; set; }
    public string? City { get; set; }
    
    // Analysis results
    public decimal RiskScore { get; set; }
    public RiskLevel RiskLevel { get; set; }
    public RecommendedAction RecommendedAction { get; set; }
    public string? RiskFactors { get; set; }  // JSON array of risk factors
    public string? Explanation { get; set; }  // Natural language explanation
    
    // Processing info
    public int ProcessingTimeMs { get; set; }
    public string? ModulesInvoked { get; set; }  // JSON array of modules
    public string? AgentsInvoked { get; set; }   // JSON array of agents
    
    // Navigation
    public virtual Tenant? Tenant { get; set; }
    public virtual FraudAlert? Alert { get; set; }
}

/// <summary>
/// Represents a fraud alert generated by the system
/// </summary>
public class FraudAlert : AuditableEntity
{
    public Guid TenantId { get; set; }
    public Guid? TransactionAnalysisId { get; set; }
    
    public required string AlertReference { get; set; }
    public AlertStatus Status { get; set; } = AlertStatus.New;
    public RiskLevel RiskLevel { get; set; }
    public decimal RiskScore { get; set; }
    
    // Alert details
    public required string Title { get; set; }
    public required string Description { get; set; }
    public string? RiskFactors { get; set; }  // JSON array
    public string? RecommendedActions { get; set; }  // JSON array
    
    // Source information
    public ModuleType SourceModule { get; set; }
    public string? SourceAgentId { get; set; }
    
    // Assignment
    public Guid? AssignedToUserId { get; set; }
    public DateTime? AssignedAt { get; set; }
    
    // Resolution
    public DateTime? ResolvedAt { get; set; }
    public string? ResolutionNotes { get; set; }
    public Guid? ResolvedByUserId { get; set; }
    
    // Escalation
    public bool IsEscalated { get; set; } = false;
    public DateTime? EscalatedAt { get; set; }
    public string? EscalationReason { get; set; }
    
    // Related entities (for linking related fraud)
    public string? RelatedEntityIds { get; set; }  // JSON array of entity IDs
    
    // Navigation
    public virtual Tenant? Tenant { get; set; }
    public virtual TransactionAnalysis? TransactionAnalysis { get; set; }
}

/// <summary>
/// Audit log for tracking all significant actions
/// </summary>
public class AuditLog : BaseEntity
{
    public Guid TenantId { get; set; }
    public Guid? UserId { get; set; }
    
    public required string Action { get; set; }
    public required string EntityType { get; set; }
    public Guid? EntityId { get; set; }
    
    public string? OldValues { get; set; }  // JSON
    public string? NewValues { get; set; }  // JSON
    
    public string? IpAddress { get; set; }
    public string? UserAgent { get; set; }
    
    public bool IsSuccess { get; set; } = true;
    public string? ErrorMessage { get; set; }
}
